### ISSUE TITLE
Restrict App Run to Single Instance

### ISSUE THREAD

**Issue by madhaven** [madhaven/proTracker#52]
Now the app will run multiple windows if opened simultaneously, this shouldn't happen.
https://stackoverflow.com/questions/35916158/how-to-prevent-multiple-instances-in-electron#

- [x] restrict instances from electron / UI
- [ ] #66

**Comment by kernelguardian** [comment]
@madhaven open for grabs?

**Comment by kernelguardian** [comment]
Latest build branch?

**Comment by madhaven** [comment]
Sorry I'm late.
Master is the latest.
Rest are all feature branches

**Comment by madhaven** [comment]
on second thoughts, having a check on the DB to reduce redundant entries would be good.
This will also help to build online hosted versions of the app to serve multiple users/instances.

Since task-clicks are directly sent to db ... this might create a duplicate entry for the same task
```
task created -> task logged done (on instance 1)
             -> task logged done (on instance 2)
```

**Comment by kernelguardian** [comment]
Sorry that I couldn’t work on it early, but depending on db for ensuring that an app runs only single instance doesn’t sound foolproof. Especially if it runs locally. Thoughts?

**Comment by madhaven** [comment]
nah the DB fix is for the future ... in case there are concurrent entries coming in.
BTW, I found an electron feature that helps restrict the app instances with a line of code.
I'll commit soon
